### ISSUE TITLE
Autofocus not working correctly with Widget

### ISSUE THREAD

**Issue by maxcountryman** [Typeform/embed#513]
It seems the `embed-focus` event mentioned in #380 is no longer available. What this means is the iframe is not autofocused when using the `Widget` component. How can this be addressed with current versions of the embed package?

**Comment by iparr** [comment]
Conversely, I'm using: `data-tf-disable-auto-focus` in an HTML embed and it steals focus.

How does one stop auto-focusing?

**Comment by antoniofull** [comment]
HI @maxcountryman @iparr thanks for reporting this, we are investigating it and we will push a fix as soon as possible. I will let you know once we have fixed it. Thanks!

**Comment by antoniofull** [comment]
HI, we have released a fix for that issue yesterday, could you let us know if now auto-focus is working fine? Thanks!

**Comment by iparr** [comment]
That seems to have done the trick, cheers.

**Comment by antoniofull** [comment]
Great! I am closing the issue, feel free to reopen it if you still have problems, thanks for reporting it.

**Comment by maxcountryman** [comment]
@antoniofull what version tag is the fix in?

**Comment by maxcountryman** [comment]
Using the latest package on NPM, this issue is not resolved for me. @antoniofull can you please reopen?

**Comment by maxcountryman** [comment]
This is still an issue using the latest available on NPM. Please reopen the issue.

Can you point me to the commit that should have addressed this?

**Comment by maxcountryman** [comment]
@antoniofull if you could reopen this, that would be great. I'm not able to.

**Comment by antoniofull** [comment]
@maxcountryman the fix was released in another package, can you explain me please what is that you cannot achieve? Thanks

**Comment by maxcountryman** [comment]
@antoniofull the issue is described in more detail [here](https://github.com/Typeform/embed/issues/513#issue-1327372676). Just to recap, this means that the keyboard controls don't work until the user manually clicks on the form.

Can you share which package you're referencing and the specific commit? Thanks!

**Comment by mathio** [comment]
Hi @maxcountryman we are aware that there was indeed an auto focus issue on August 3rd. The issue was not in the embed library, however in the typeform itself. However the issue has been resolved since. 

Are you still experiencing any issues with auto focus? If yes, can you show as an example of embedded typeform with the issue? Thanks.

**Comment by maxcountryman** [comment]
@mathio can you please reference the commit that you believe addressed the issue?

**Comment by maxcountryman** [comment]
@mathio okay well whatever fix was made did not address the missing event issue I raised in this ticket. It also did not address that an embedded Widget will not autofocus.

**Comment by mathio** [comment]
I am happy to report the focus was fixed earlier this week. Your embedded widgets will now autofocus unless it is explicitly disabled via `disableAutoFocus` option.

**Comment by mathio** [comment]
There was an update to the auto focus feature recently: https://github.com/Typeform/embed/pull/521

It is disabled by default for widget / standard embeds. It can be enabled via `data-tf-auto-focus` or `autoFocus: true` option. Or you can focus programmatically via the newly exposed `focus()` method.

More in my [blog post](https://mathio28.medium.com/widget-auto-focus-in-embed-sdk-8e0c0584b57).
